linters:
  enable-all: true
  disable:
  - golint # unsupported
  - maligned # unsupported
  - scopelint # unsupported
  - interfacer # unsupported
  - paralleltest # doesn't work for Ginkgo tests
  - exhaustivestruct
linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
