name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Start test environment
        run: docker-compose -f "docker/docker-compose.yml" up -d

      - name: Test
        timeout-minutes: 10
        env:
          FORM3_API_URL: http://localhost:8080/v1
        run: ginkgo --label-filter="e2e" --output-dir=test-reports --junit-report=e2e_test_report.xml --keep-separate-reports --keep-separate-coverprofiles -v -r --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --race --trace

      - name: Stop test environment
        if: always()
        run: docker-compose -f "docker/docker-compose.yml" down

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests-results
          path: test-reports
