name: E2E test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.0.0

      - name: Start environment
        run: docker-compose -f "docker/docker-compose.yml" up -d

      - name: Test
        timeout-minutes: 10
        env:
          FORM3_API_URL: http://localhost:8080/v1
        run: ginkgo --label-filter=e2e --junit-report=test_report_e2e.xml -v -r --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --race --trace

      # - name: Archive test results as annotations
      #   uses: EnricoMi/publish-unit-test-result-action@v1
      #   if: always()
      #   with:
      #     files: test_report_e2e.xml

      # TODO TESTING
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: "**/test_report_e2e.xml"

      # TODO TESTING
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests-results
          path: "**/test_report_e2e.xml"

      - name: Stop environment
        if: always()
        run: docker-compose -f "docker/docker-compose.yml" down
