name: Static analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: go vet
        run: go vet ./...

      - name: Install GoLint
        run: go install golang.org/x/lint/golint@latest

      - name: golint
        run: golint -set_exit_status ./...
