name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.0.0

      - name: Test
        timeout-minutes: 10
        run: ginkgo --label-filter="!e2e" --output-dir=test-reports --junit-report=test_report.xml --keep-separate-reports --keep-separate-coverprofiles -v -r --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --race --trace

      - name: List files
        run: find .

      # TODO TESTING
      - name: Archive test results as annotations
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test-reports/*test_report.xml"

      # TODO TESTING
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: "test-reports/*test_report.xml"

      # TODO TESTING
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests-results
          path: test-reports

      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "test-reports/*test_report.xml"
